package com.bonc.kafkamsg;

import java.util.Hashtable;
import java.util.Map;

public class CountryUtil {
	public static Map<String,String> countryMap=new Hashtable<String,String>();
	static{
		countryMap.put("Afghanistan", "阿富汗");
		countryMap.put("阿富汗", "Afghanistan");
		countryMap.put("Albania", "阿尔巴尼亚");
		countryMap.put("阿尔巴尼亚", "Albania");
		countryMap.put("Algeria", "阿尔及利亚");
		countryMap.put("阿尔及利亚", "Algeria");
		countryMap.put("Andorra", "安道尔共和国");
		countryMap.put("安道尔共和国", "Andorra");
		countryMap.put("Anguilla", "安圭拉岛");
		countryMap.put("安圭拉岛", "Anguilla");
		countryMap.put("Antigua and Barbuda", "安提瓜和巴布达");
		countryMap.put("安提瓜和巴布达", "Antigua and Barbuda");
		countryMap.put("Argentina", "阿根廷");
		countryMap.put("阿根廷", "Argentina");
		countryMap.put("Armenia", "亚美尼亚");
		countryMap.put("亚美尼亚", "Armenia");
		countryMap.put("Ascension", "阿森松");
		countryMap.put("阿森松", "Ascension");
		countryMap.put("Australia", "澳大利亚");
		countryMap.put("澳大利亚", "Australia");
		countryMap.put("Austria", "奥地利");
		countryMap.put("奥地利", "Austria");
		countryMap.put("Azerbaijan", "阿塞拜疆");
		countryMap.put("阿塞拜疆", "Azerbaijan");
		countryMap.put("Bahamas", "巴哈马");
		countryMap.put("巴哈马", "Bahamas");
		countryMap.put("Bahrain", "巴林");
		countryMap.put("巴林", "Bahrain");
		countryMap.put("Bangladesh", "孟加拉国");
		countryMap.put("孟加拉国", "Bangladesh");
		countryMap.put("Barbados", "巴巴多斯");
		countryMap.put("巴巴多斯", "Barbados");
		countryMap.put("Belarus", "白俄罗斯");
		countryMap.put("白俄罗斯", "Belarus");
		countryMap.put("Belgium", "比利时");
		countryMap.put("比利时", "Belgium");
		countryMap.put("Belize", "伯利兹");
		countryMap.put("伯利兹", "Belize");
		countryMap.put("Benin", "贝宁");
		countryMap.put("贝宁", "Benin");
		countryMap.put("Bermuda", "百慕大群岛");
		countryMap.put("百慕大群岛", "Bermuda");
		countryMap.put("Bolivia", "玻利维亚");
		countryMap.put("玻利维亚", "Bolivia");
		countryMap.put("Botswana", "博茨瓦纳");
		countryMap.put("博茨瓦纳", "Botswana");
		countryMap.put("Brazil", "巴西");
		countryMap.put("巴西", "Brazil");
		countryMap.put("Brunei", "文莱");
		countryMap.put("文莱", "Brunei");
		countryMap.put("Bulgaria", "保加利亚");
		countryMap.put("保加利亚", "Bulgaria");
		countryMap.put("Burkina Faso", "布基纳法索");
		countryMap.put("布基纳法索", "Burkina Faso");
		countryMap.put("Burma", "缅甸");
		countryMap.put("缅甸", "Burma");
		countryMap.put("Burundi", "布隆迪");
		countryMap.put("布隆迪", "Burundi");
		countryMap.put("Cameroon", "喀麦隆");
		countryMap.put("喀麦隆", "Cameroon");
		countryMap.put("Canada", "加拿大");
		countryMap.put("加拿大", "Canada");
		countryMap.put("Cayman Islands", "开曼群岛");
		countryMap.put("开曼群岛", "Cayman Islands");
		countryMap.put("Central African Republic", "中非共和国");
		countryMap.put("中非共和国", "Central African Republic");
		countryMap.put("Chad", "乍得");
		countryMap.put("乍得", "Chad");
		countryMap.put("Chile", "智利");
		countryMap.put("智利", "Chile");
		countryMap.put("China", "中国");
		countryMap.put("中国", "China");
		countryMap.put("Colombia", "哥伦比亚");
		countryMap.put("哥伦比亚", "Colombia");
		countryMap.put("Congo", "刚果");
		countryMap.put("刚果", "Congo");
		countryMap.put("Cook Islands", "库克群岛");
		countryMap.put("库克群岛", "Cook Islands");
		countryMap.put("Costa Rica", "哥斯达黎加");
		countryMap.put("哥斯达黎加", "Costa Rica");
		countryMap.put("Cuba", "古巴");
		countryMap.put("古巴", "Cuba");
		countryMap.put("Cyprus", "塞浦路斯");
		countryMap.put("塞浦路斯", "Cyprus");
		countryMap.put("Czech Republic", "捷克");
		countryMap.put("捷克", "Czech Republic");
		countryMap.put("Denmark", "丹麦");
		countryMap.put("丹麦", "Denmark");
		countryMap.put("Djibouti", "吉布提");
		countryMap.put("吉布提", "Djibouti");
		countryMap.put("Dominican Republic", "多米尼加共和国");
		countryMap.put("多米尼加共和国", "Dominican Republic");
		countryMap.put("Ecuador", "厄瓜多尔");
		countryMap.put("厄瓜多尔", "Ecuador");
		countryMap.put("Egypt", "埃及");
		countryMap.put("埃及", "Egypt");
		countryMap.put("Salvador", "萨尔瓦多");
		countryMap.put("萨尔瓦多", "Salvador");
		countryMap.put("Estonia", "爱沙尼亚");
		countryMap.put("爱沙尼亚", "Estonia");
		countryMap.put("Ethiopia", "埃塞俄比亚");
		countryMap.put("埃塞俄比亚", "Ethiopia");
		countryMap.put("Fiji", "斐济");
		countryMap.put("斐济", "Fiji");
		countryMap.put("Finland", "芬兰");
		countryMap.put("芬兰", "Finland");
		countryMap.put("France", "法国");
		countryMap.put("法国", "France");
		countryMap.put("French Guiana", "法属圭亚那");
		countryMap.put("法属圭亚那", "French Guiana");
		countryMap.put("Gabon", "加蓬");
		countryMap.put("加蓬", "Gabon");
		countryMap.put("Gambia", "冈比亚");
		countryMap.put("冈比亚", "Gambia");
		countryMap.put("Georgia", "格鲁吉亚");
		countryMap.put("格鲁吉亚", "Georgia");
		countryMap.put("Germany", "德国");
		countryMap.put("德国", "Germany");
		countryMap.put("Ghana", "加纳");
		countryMap.put("加纳", "Ghana");
		countryMap.put("Gibraltar", "直布罗陀");
		countryMap.put("直布罗陀", "Gibraltar");
		countryMap.put("Greece", "希腊");
		countryMap.put("希腊", "Greece");
		countryMap.put("Grenada", "格林纳达");
		countryMap.put("格林纳达", "Grenada");
		countryMap.put("Guam", "关岛");
		countryMap.put("关岛", "Guam");
		countryMap.put("Guatemala", "危地马拉");
		countryMap.put("危地马拉", "Guatemala");
		countryMap.put("Guinea", "几内亚");
		countryMap.put("几内亚", "Guinea");
		countryMap.put("Guyana", "圭亚那");
		countryMap.put("圭亚那", "Guyana");
		countryMap.put("Haiti", "海地");
		countryMap.put("海地", "Haiti");
		countryMap.put("Honduras", "洪都拉斯");
		countryMap.put("洪都拉斯", "Honduras");
		countryMap.put("Hong Kong", "香港");
		countryMap.put("香港", "Hong Kong");
		countryMap.put("Hungary", "匈牙利");
		countryMap.put("匈牙利", "Hungary");
		countryMap.put("Iceland", "冰岛");
		countryMap.put("冰岛", "Iceland");
		countryMap.put("India", "印度");
		countryMap.put("印度", "India");
		countryMap.put("Indonesia", "印度尼西亚");
		countryMap.put("印度尼西亚", "Indonesia");
		countryMap.put("Iran", "伊朗");
		countryMap.put("伊朗", "Iran");
		countryMap.put("Iraq", "伊拉克");
		countryMap.put("伊拉克", "Iraq");
		countryMap.put("Ireland", "爱尔兰");
		countryMap.put("爱尔兰", "Ireland");
		countryMap.put("Israel", "以色列");
		countryMap.put("以色列", "Israel");
		countryMap.put("Italy", "意大利");
		countryMap.put("意大利", "Italy");
		countryMap.put("Cote d'Ivoire", "科特迪瓦");
		countryMap.put("科特迪瓦", "Cote d'Ivoire");
		countryMap.put("Jamaica", "牙买加");
		countryMap.put("牙买加", "Jamaica");
		countryMap.put("Japan", "日本");
		countryMap.put("日本", "Japan");
		countryMap.put("Jordan", "约旦");
		countryMap.put("约旦", "Jordan");
		countryMap.put("Cambodia", "柬埔寨");
		countryMap.put("柬埔寨", "Cambodia");
		countryMap.put("Kazakhstan", "哈萨克斯坦");
		countryMap.put("哈萨克斯坦", "Kazakhstan");
		countryMap.put("Kenya", "肯尼亚");
		countryMap.put("肯尼亚", "Kenya");
		countryMap.put("Korea", "韩国");
		countryMap.put("韩国", "Korea");
		countryMap.put("Kuwait", "科威特");
		countryMap.put("科威特", "Kuwait");
		countryMap.put("Kyrgyzstan", "吉尔吉斯坦");
		countryMap.put("吉尔吉斯坦", "Kyrgyzstan");
		countryMap.put("Laos", "老挝");
		countryMap.put("老挝", "Laos");
		countryMap.put("Latvia", "拉脱维亚");
		countryMap.put("拉脱维亚", "Latvia");
		countryMap.put("Lebanon", "黎巴嫩");
		countryMap.put("黎巴嫩", "Lebanon");
		countryMap.put("Lesotho", "莱索托");
		countryMap.put("莱索托", "Lesotho");
		countryMap.put("Liberia", "利比里亚");
		countryMap.put("利比里亚", "Liberia");
		countryMap.put("Libya", "利比亚");
		countryMap.put("利比亚", "Libya");
		countryMap.put("Liechtenstein", "列支敦士登");
		countryMap.put("列支敦士登", "Liechtenstein");
		countryMap.put("Lithuania", "立陶宛");
		countryMap.put("立陶宛", "Lithuania");
		countryMap.put("Luxembourg", "卢森堡");
		countryMap.put("卢森堡", "Luxembourg");
		countryMap.put("Macao", "澳门");
		countryMap.put("澳门", "Macao");
		countryMap.put("Madagascar", "马达加斯加");
		countryMap.put("马达加斯加", "Madagascar");
		countryMap.put("Malawi", "马拉维");
		countryMap.put("马拉维", "Malawi");
		countryMap.put("Malaysia", "马来西亚");
		countryMap.put("马来西亚", "Malaysia");
		countryMap.put("Maldives", "马尔代夫");
		countryMap.put("马尔代夫", "Maldives");
		countryMap.put("Mali", "马里");
		countryMap.put("马里", "Mali");
		countryMap.put("Malta", "马耳他");
		countryMap.put("马耳他", "Malta");
		countryMap.put("Mariana Is", "马里亚那群岛");
		countryMap.put("马里亚那群岛", "Mariana Is");
		countryMap.put("Martinique", "马提尼克");
		countryMap.put("马提尼克", "Martinique");
		countryMap.put("Mauritius", "毛里求斯");
		countryMap.put("毛里求斯", "Mauritius");
		countryMap.put("Mexico", "墨西哥");
		countryMap.put("墨西哥", "Mexico");
		countryMap.put("Moldova", "摩尔多瓦");
		countryMap.put("摩尔多瓦", "Moldova");
		countryMap.put("Monaco", "摩纳哥");
		countryMap.put("摩纳哥", "Monaco");
		countryMap.put("Mongolia", "蒙古");
		countryMap.put("蒙古", "Mongolia");
		countryMap.put("Montserrat Is", "蒙特塞拉特岛");
		countryMap.put("蒙特塞拉特岛", "Montserrat Is");
		countryMap.put("Morocco", "摩洛哥");
		countryMap.put("摩洛哥", "Morocco");
		countryMap.put("Mozambique", "莫桑比克");
		countryMap.put("莫桑比克", "Mozambique");
		countryMap.put("Namibia", "纳米比亚");
		countryMap.put("纳米比亚", "Namibia");
		countryMap.put("Nauru", "瑙鲁");
		countryMap.put("瑙鲁", "Nauru");
		countryMap.put("Nepal", "尼泊尔");
		countryMap.put("尼泊尔", "Nepal");
		countryMap.put("Netheriands Antilles", "荷属安的列斯");
		countryMap.put("荷属安的列斯", "Netheriands Antilles");
		countryMap.put("Netherlands", "荷兰");
		countryMap.put("荷兰", "Netherlands");
		countryMap.put("New Zealand", "新西兰");
		countryMap.put("新西兰", "New Zealand");
		countryMap.put("Nicaragua", "尼加拉瓜");
		countryMap.put("尼加拉瓜", "Nicaragua");
		countryMap.put("Niger", "尼日尔");
		countryMap.put("尼日尔", "Niger");
		countryMap.put("Nigeria", "尼日利亚");
		countryMap.put("尼日利亚", "Nigeria");
		countryMap.put("North Korea", "朝鲜");
		countryMap.put("朝鲜", "North Korea");
		countryMap.put("Norway", "挪威");
		countryMap.put("挪威", "Norway");
		countryMap.put("Oman", "阿曼");
		countryMap.put("阿曼", "Oman");
		countryMap.put("Pakistan", "巴基斯坦");
		countryMap.put("巴基斯坦", "Pakistan");
		countryMap.put("Panama", "巴拿马");
		countryMap.put("巴拿马", "Panama");
		countryMap.put("Papua New Cuinea", "巴布亚新几内亚");
		countryMap.put("巴布亚新几内亚", "Papua New Cuinea");
		countryMap.put("Paraguay", "巴拉圭");
		countryMap.put("巴拉圭", "Paraguay");
		countryMap.put("Peru", "秘鲁");
		countryMap.put("秘鲁", "Peru");
		countryMap.put("Philippines", "菲律宾");
		countryMap.put("菲律宾", "Philippines");
		countryMap.put("Poland", "波兰");
		countryMap.put("波兰", "Poland");
		countryMap.put("French Polynesia", "法属玻利尼西亚");
		countryMap.put("法属玻利尼西亚", "French Polynesia");
		countryMap.put("Portugal", "葡萄牙");
		countryMap.put("葡萄牙", "Portugal");
		countryMap.put("Puerto Rico", "波多黎各");
		countryMap.put("波多黎各", "Puerto Rico");
		countryMap.put("Qatar", "卡塔尔");
		countryMap.put("卡塔尔", "Qatar");
		countryMap.put("Reunion", "留尼旺");
		countryMap.put("留尼旺", "Reunion");
		countryMap.put("Romania", "罗马尼亚");
		countryMap.put("罗马尼亚", "Romania");
		countryMap.put("Russia", "俄罗斯");
		countryMap.put("俄罗斯", "Russia");
		countryMap.put("Saint Lueia", "圣卢西亚");
		countryMap.put("圣卢西亚", "Saint Lueia");
		countryMap.put("Saint Vincent", "圣文森特岛");
		countryMap.put("圣文森特岛", "Saint Vincent");
		countryMap.put("Samoa Eastern", "东萨摩亚(美)");
		countryMap.put("东萨摩亚(美)", "Samoa Eastern");
		countryMap.put("Samoa Western", "西萨摩亚");
		countryMap.put("西萨摩亚", "Samoa Western");
		countryMap.put("San Marino", "圣马力诺");
		countryMap.put("圣马力诺", "San Marino");
		countryMap.put("Sao Tome and Principe", "圣多美和普林西比");
		countryMap.put("圣多美和普林西比", "Sao Tome and Principe");
		countryMap.put("Saudi Arabia", "沙特阿拉伯");
		countryMap.put("沙特阿拉伯", "Saudi Arabia");
		countryMap.put("Senegal", "塞内加尔");
		countryMap.put("塞内加尔", "Senegal");
		countryMap.put("Seychelles", "塞舌尔");
		countryMap.put("塞舌尔", "Seychelles");
		countryMap.put("Sierra Leone", "塞拉利昂");
		countryMap.put("塞拉利昂", "Sierra Leone");
		countryMap.put("Singapore", "新加坡");
		countryMap.put("新加坡", "Singapore");
		countryMap.put("Slovakia", "斯洛伐克");
		countryMap.put("斯洛伐克", "Slovakia");
		countryMap.put("Slovenia", "斯洛文尼亚");
		countryMap.put("斯洛文尼亚", "Slovenia");
		countryMap.put("Solomon Islands", "所罗门群岛");
		countryMap.put("所罗门群岛", "Solomon Islands");
		countryMap.put("Somalia", "索马里");
		countryMap.put("索马里", "Somalia");
		countryMap.put("South Africa", "南非");
		countryMap.put("南非", "South Africa");
		countryMap.put("Spain", "西班牙");
		countryMap.put("西班牙", "Spain");
		countryMap.put("Sri Lanka", "斯里兰卡");
		countryMap.put("斯里兰卡", "Sri Lanka");
		countryMap.put("St.Vincent", "圣文森特");
		countryMap.put("圣文森特", "St.Vincent");
		countryMap.put("Sudan", "苏丹");
		countryMap.put("苏丹", "Sudan");
		countryMap.put("Surinam", "苏里南");
		countryMap.put("苏里南", "Surinam");
		countryMap.put("Swaziland", "斯威士兰");
		countryMap.put("斯威士兰", "Swaziland");
		countryMap.put("Sweden", "瑞典");
		countryMap.put("瑞典", "Sweden");
		countryMap.put("Switzerland", "瑞士");
		countryMap.put("瑞士", "Switzerland");
		countryMap.put("Syria", "叙利亚");
		countryMap.put("叙利亚", "Syria");
		countryMap.put("Taiwan", "台湾省");
		countryMap.put("台湾省", "Taiwan");
		countryMap.put("Tajikistan", "塔吉克斯坦");
		countryMap.put("塔吉克斯坦", "Tajikistan");
		countryMap.put("Tanzania", "坦桑尼亚");
		countryMap.put("坦桑尼亚", "Tanzania");
		countryMap.put("Thailand", "泰国");
		countryMap.put("泰国", "Thailand");
		countryMap.put("Togo", "多哥");
		countryMap.put("多哥", "Togo");
		countryMap.put("Tonga", "汤加");
		countryMap.put("汤加", "Tonga");
		countryMap.put("Trinidad and Tobago", "特立尼达和多巴哥");
		countryMap.put("特立尼达和多巴哥", "Trinidad and Tobago");
		countryMap.put("Tunisia", "突尼斯");
		countryMap.put("突尼斯", "Tunisia");
		countryMap.put("Turkey", "土耳其");
		countryMap.put("土耳其", "Turkey");
		countryMap.put("Turkmenistan", "土库曼斯坦");
		countryMap.put("土库曼斯坦", "Turkmenistan");
		countryMap.put("Uganda", "乌干达");
		countryMap.put("乌干达", "Uganda");
		countryMap.put("Ukraine", "乌克兰");
		countryMap.put("乌克兰", "Ukraine");
		countryMap.put("United Arab Emirates", "阿拉伯联合酋长国");
		countryMap.put("阿拉伯联合酋长国", "United Arab Emirates");
		countryMap.put("United Kingdom", "英国");
		countryMap.put("英国", "United Kingdom");
		countryMap.put("United States", "美国");
		countryMap.put("美国", "United States");
		countryMap.put("Uruguay", "乌拉圭");
		countryMap.put("乌拉圭", "Uruguay");
		countryMap.put("Uzbekistan", "乌兹别克斯坦");
		countryMap.put("乌兹别克斯坦", "Uzbekistan");
		countryMap.put("Venezuela", "委内瑞拉");
		countryMap.put("委内瑞拉", "Venezuela");
		countryMap.put("Vietnam", "越南");
		countryMap.put("越南", "Vietnam");
		countryMap.put("Yemen", "也门");
		countryMap.put("也门", "Yemen");
		countryMap.put("Yugoslavia", "南斯拉夫");
		countryMap.put("南斯拉夫", "Yugoslavia");
		countryMap.put("Zimbabwe", "津巴布韦");
		countryMap.put("津巴布韦", "Zimbabwe");
		countryMap.put("Zaire", "扎伊尔");
		countryMap.put("扎伊尔", "Zaire");
		countryMap.put("Zambia", "赞比亚");
		countryMap.put("赞比亚", "Zambia");
		countryMap.put("Other", "其他");
		countryMap.put("其他", "Other");
	}
	public  String getCountry (String country){
		return countryMap.get(country);
	}
}
